/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "generate_random_number.baml": "function GenerateRandomNumber() -> RandomNumber {\n  client Gemini\n  prompt #\"\n    Generate a random number between 1 and 100.\n    Return only the number, nothing else.\n  \"#\n}\n",
  "generate_random_number.tests.baml": "test TestGenerateRandomNumber {\n  functions [GenerateRandomNumber]\n  args {}\n}\n",
  "llm_clients/gemini.baml": "client<llm> Gemini {\n  provider google-ai\n  options {\n    model gemini-2.5-pro\n    api_key env.GEMINI_API_KEY\n  }\n}\n",
  "schema.baml": "class RandomNumber {\n  number int\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}